### ISSUE TITLE
feature: Use Github's CI to update the lists weekly rather than using a local method

### ISSUE THREAD

**Issue by T145** [fuatboluk/usom-blacklist#1]
If you commit the scripts you've used to perform the updates I can handle the automation if you'd like.

**Comment by fuatboluk** [comment]
It would be great if you do this. I couldn't deal with the density. Thank you very much for your help.

**Comment by T145** [comment]
Happy to help: just be sure to commit the scripts that perform the updates.

**Comment by fuatboluk** [comment]
Everything is in this warehouse. I manually include the output files to the relevant service within the system and restart the service. so that new updates are active. This is how I planned it. However, I couldn't deal with it afterwards because my work was very busy. It would be a much more useful update system if we could automate the periodic rebuilding of new config files and the ability to pull from a hard link.

**Comment by fuatboluk** [comment]
Thanks again for your contribution. Workflows worked and updated files. However, some errors occurred. The errors are as follows.

Start time      : 22:31:23
Description     : USOM malicious ip addresses and domains blacklist!
Original url    : https://www.usom.gov.tr/url-list.txt
## Listing all active malicious ips...
## Listing all active malicious domains...
  Connected     : armtheprofileoriginals.com
  Connected     : bit.ly
  Not connected : dedicatematch.top
  Not connected : dijitalbasvurumobildenizgiris.co.vu
  Not connected : doseoul.com
  Connected     : firebasestorage.googleapis.com
  Connected     : haeundaejugong.com
  Not connected : hz11.cn
  Connected     : igstalk.com
  Connected     : kjdnc.gp114.net
  Connected     : kumdo.org
  Connected     : kutt.it
  Connected     : luminix.kr
  Connected     : luminix.openhaja.com
  Connected     : organmelody.top
  Not connected : paribdunya.destekparibe.click
  Connected     : priortable.top
  Connected     : rebrand.ly
  Not connected : twittetakip.com
  Connected     : utka.su
  Connected     : ylhwcl.com
sort: cannot read: /tmp/all-ip-blacklist.txt: No such file or directory
## All malicious ip addresses and domains blacklisted!
  /home/runner/work/usom-blacklist/usom-blacklist/ip-blacklist.txt
  /home/runner/work/usom-blacklist/usom-blacklist/domain-blacklist.txt
cat: /tmp/all-ip-blacklist.txt: No such file or directory
## Local blacklists created!
  /home/runner/work/usom-blacklist/usom-blacklist/etc-hosts.txt
  /home/runner/work/usom-blacklist/usom-blacklist/unbound-conf.txt
End time        : 22:31:46
Elapsed time    : 00:00:23
Completed!

**Comment by T145** [comment]
The error is b/c since there were no IPs from USOM then `/tmp/all-ip-blacklist.txt` was never created. All you need to do is check if the file exists before trying to read from it. It would be something like this:
```bash
if test -f '/tmp/all-ip-blacklist.txt'; then
  # ...
fi
```

**Comment by fuatboluk** [comment]
I've never seen data added to this list get deleted before. :) I think they removed their ip addresses.

**Comment by fuatboluk** [comment]
I refactored the check-usom-list script, ran it on my computer and tested it. It works successfully and I have written the final output to the README.md file. However, the Workflow completed before the check process completes and writed the missing list. The script I ran on the local machine completed in 55 minutes. How can we extend this time for workflow job?

**Comment by T145** [comment]
My guess is that the host is blacklisting your IP from downloading any more files for a while. There are several services I've come across that do this to rate-limit how many people or bots download the lists and correspondingly burden their servers. It's the only conclusion I can come to after the first bulid only took 10 minutes and the fact that your current job hasn't printed any output yet.

**Comment by fuatboluk** [comment]
I ran it again and it successfully updated all files.
